import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const pixelFont = localFont({
  src: '../../public/fonts/pixel.woff',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
